In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('rendimiento_2010-2022.csv', sep=',', encoding='latin-1')

In [2]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [3]:
df.dtypes

AGNO             int64
COD_DEPE         int64
COD_REG_RBD      int64
COD_ENSE         int64
PROM_GRAL      float64
dtype: object

In [4]:
df

          AGNO  COD_DEPE  COD_REG_RBD  COD_ENSE  PROM_GRAL
0         2010         2           15       610        5.7
1         2010         2           15       610        5.8
2         2010         2           15       510        0.0
3         2010         2           15       510        5.2
4         2010         2           15       510        5.1
...        ...       ...          ...       ...        ...
40241526  2022         3           13       310        0.0
40241527  2022         3           13       310        0.0
40241528  2022         3           13       310        0.0
40241529  2022         3           13       310        0.0
40241530  2022         3           13       310        0.0

[40241531 rows x 5 columns]

In [5]:
# Assuming df is your DataFrame
df = df[~df['COD_DEPE'].isin([5, 6])]

# Replace the codes in 'COD_DEPE' with their corresponding institution type
df['COD_DEPE'] = df['COD_DEPE'].replace({1: 'Municipal', 2: 'Municipal', 3: 'Particular Subvencionado', 4: 'Particular Pagado'})
df['COD_ENSE'] = df['COD_ENSE'].replace({110: 'Educacion Basica', 310: 'Educacion Media', 410: "Educacion Media", 510: "Educacion Media", 610: "Educacion Media", 710: "Educacion Media",
                                         810: "Educacion Media", 910: "Educacion Media"})
df['COD_REG_RBD'] = df['COD_REG_RBD'].replace({
    15: "Región de Arica y Parinacota",
    1: "Región de Tarapacá",
    2: "Región de Antofagasta",
    3: "Región de Atacama",
    4: "Región de Coquimbo",
    5: "Región de Valparaíso",
    6: "Región del Libertador Bernardo O'Higgins",
    7: "Región del Maule",
    16: "Región de Ñuble",
    8: "Región del Bío-Bío",
    9: "Región de La Araucanía",
    14: "Región de Los Ríos",
    10: "Región de Los Lagos",
    11: "Región de Aysén del Gral. Ibañez del Campo",
    12: "Región de Magallanes y Antártica Chilena",
    13: "Región Metropolitana de Santiago",
})
# Now group by 'AGNO', 'COD_DEPE', 'COD_REG_RBD', and 'COD_ENSE', and compute the mean of 'PROM_GRAL'
new_df = df.groupby(['AGNO', 'COD_DEPE', 'COD_REG_RBD', 'COD_ENSE'])['PROM_GRAL'].mean().reset_index()

/var/folders/l5/2rxggm8s7mv2g33kfr8sbw780000gn/T/ipykernel_14865/4026578769.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['COD_DEPE'] = df['COD_DEPE'].replace({1: 'Municipal', 2: 'Municipal', 3: 'Particular Subvencionado', 4: 'Particular Pagado'})
/var/folders/l5/2rxggm8s7mv2g33kfr8sbw780000gn/T/ipykernel_14865/4026578769.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['COD_ENSE'] = df['COD_ENSE'].replace({110: 'Educacion Basica', 310: 'Educacion Media', 410: "Educacion Media", 510: "Educacion Media", 610: "Educacion Media", 710: "Educacion Media",
/var/folders/l5/2rxggm8s7mv2g33kfr8sbw780000gn/T/ipykernel_14865/4026578769.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['COD_REG_RBD'] = df['COD_REG_RBD'].replace({

In [6]:
new_df

,AGNO,COD_DEPE,COD_REG_RBD,COD_ENSE,PROM_GRAL
0,2010,Municipal,Región Metropolitana de Santiago,Educacion Basica,5.165412
1,2010,Municipal,Región Metropolitana de Santiago,Educacion Media,4.655421
2,2010,Municipal,Región de Antofagasta,Educacion Basica,5.351091
3,2010,Municipal,Región de Antofagasta,Educacion Media,4.618547
4,2010,Municipal,Región de Arica y Parinacota,Educacion Basica,5.500399
...,...,...,...,...,...
1157,2022,Particular Subvencionado,Región del Bío-Bío,Educacion Media,5.664011
1158,2022,Particular Subvencionado,Región del Libertador Bernardo O'Higgins,Educacion Basica,5.815795
1159,2022,Particular Subvencionado,Región del Libertador Bernardo O'Higgins,Educacion Media,5.546832
1160,2022,Particular Subvencionado,Región del Maule,Educacion Basica,5.877327
1161,2022,Particular Subvencionado,Región del Maule,Educacion Media,5.519590

In [7]:
## Export to csv
new_df.to_csv('resumen_rendimiento_2010-2022.csv', index=False)

In [8]:
## Now we can see only the rows asociated to the 'COD_REG_RBD' == "Region de Atacama"
new_df[new_df['COD_REG_RBD'] == "Atacama"]

Empty DataFrame
Columns: [AGNO, COD_DEPE, COD_REG_RBD, COD_ENSE, PROM_GRAL]
Index: []

In [9]:
# Now group by 'AGNO' and 'COD_DEPE', and compute the mean of 'PROM_GRAL'
df_prom_gral_comb = df.groupby(['AGNO', 'COD_DEPE'])['PROM_GRAL'].mean().reset_index()

# Rename the column
df_prom_gral_comb.rename(columns={'PROM_GRAL': 'PROM_GRAL_COMB'}, inplace=True)

In [10]:
df_prom_gral_comb

    AGNO                  COD_DEPE  PROM_GRAL_COMB
0   2010                 Municipal        5.098783
1   2010         Particular Pagado        5.827674
2   2010  Particular Subvencionado        5.360188
3   2011                 Municipal        4.982172
4   2011         Particular Pagado        5.770831
5   2011  Particular Subvencionado        5.260753
6   2012                 Municipal        4.958066
7   2012         Particular Pagado        5.719647
8   2012  Particular Subvencionado        5.206968
9   2013                 Municipal        5.008290
10  2013         Particular Pagado        5.785539
11  2013  Particular Subvencionado        5.263463
12  2014                 Municipal        5.070469
13  2014         Particular Pagado        5.861268
14  2014  Particular Subvencionado        5.307292
15  2015                 Municipal        5.083715
16  2015         Particular Pagado        5.874302
17  2015  Particular Subvencionado        5.329199
18  2016                 Municipal        5.161759
19  2016         Particular Pagado        5.944655
20  2016  Particular Subvencionado        5.367704
21  2017                 Municipal        5.221705
22  2017         Particular Pagado        5.965865
23  2017  Particular Subvencionado        5.392848
24  2018                 Municipal        5.225811
25  2018         Particular Pagado        5.960491
26  2018  Particular Subvencionado        5.404433
27  2019                 Municipal        5.282053
28  2019         Particular Pagado        5.995468
29  2019  Particular Subvencionado        5.431845
30  2020                 Municipal        5.688575
31  2020         Particular Pagado        6.175728
32  2020  Particular Subvencionado        5.924574
33  2021                 Municipal        5.661512
34  2021         Particular Pagado        6.186678
35  2021  Particular Subvencionado        5.848137
36  2022                 Municipal        5.382023
37  2022         Particular Pagado        6.130468
38  2022  Particular Subvencionado        5.613276

In [11]:
## Export as csv
df_prom_gral_comb.to_csv('promedio_general_por_tipo_institucion_2010-2022.csv', index=False)